### ISSUE TITLE
Source filtering use cases

### ISSUE THREAD

**Issue by rubensworks** [rdfjs/query-spec#1]
As discussed in rdfjs/stream-spec#16, this issue serves as a place to collect use cases for why additional filtering capabilities are needed in the `Source` interface.

**Comment by jacoscaz** [comment]
Following from https://github.com/rdfjs/data-model-spec/issues/167#issuecomment-674745495 and https://github.com/rdfjs/data-model-spec/issues/167#issuecomment-675344924, I’d like to address @rubensworks’ following concern:

> A pipeline-based architecture is interested, I hadn't thought of that before. I'm just wondering if it's expressive enough for all types of queries. I would suspect recursive filter definitions may be a bit more expressive, which is what SPARQL algebra does.

I think you are definitely right - recursive definitions are more expressive. However, they also seem to be significantly harder to deal with from a development perspective and for `quadstore` I‘ve intentionally opted for a compromise between the two that allows me to keep the optimization part of the codebase relatively straightforward. In particular, I have found that re-ordering queries by their approximate counts (something I am still working on) becomes a mess really quickly when using the recursive approach. Granted, this could be due to a deficiency on my side rather than an objective difference in handling complexity but be as it may, I find myself having a much easier time when adopting the pipeline approach.

I am not at all opposed to recursiveness, though, and I will get a chance to explore that further once I move to switch from `sparqljs` to `sparqlalgebrajs` in version 8.

**Comment by rubensworks** [comment]
Done in #4.
